CREATE  DATABASE SQL_PROJECT;
USE SQL_PROJECT;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    SupplierID TINYINT PRIMARY KEY AUTO_INCREMENT,
    SupplierName VARCHAR(255),
    Address TEXT
);
SELECT * FROM supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    CategoryID TINYINT PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(255)
);
SELECT * FROM categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    EmployeeID TINYINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    HireDate VARCHAR(255)
);
SELECT * FROM employees;
-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    CustomerID SMALLINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    Address TEXT
);

select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    ProductID TINYINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    SupplierID TINYINT,
    CategoryID TINYINT,
    Price DECIMAL(10,2),
    FOREIGN KEY (SupplierID) REFERENCES supplier(SupplierID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES categories(CategoryID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    OrderID SMALLINT PRIMARY KEY AUTO_INCREMENT,
    CustomerID SMALLINT,
    EmployeeID TINYINT,
    OrderDate VARCHAR(255),
    FOREIGN KEY (CustomerID) REFERENCES customers(CustomerID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EmployeeID) REFERENCES employees(EmployeeID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    OrderDetailID SMALLINT PRIMARY KEY AUTO_INCREMENT,
    OrderID SMALLINT,
    ProductID TINYINT,
    Quantity TINYINT,
    PriceEach DECIMAL(10,2),
    TotalPrice DECIMAL(10,2),
    FOREIGN KEY (OrderID) REFERENCES orders(OrderID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES products(ProductID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from order_details;

SET SQL_SAFE_UPDATES = 0;
UPDATE orders
SET OrderDate = STR_TO_DATE(OrderDate, '%m/%d/%Y');

ALTER TABLE orders
MODIFY OrderDate DATE;

UPDATE employees
SET HireDate = STR_TO_DATE(HireDate, '%m/%d/%Y');

ALTER TABLE employees
MODIFY HireDate DATE;

/* 1️. Customer Insights
Gain an understanding of customer engagement and purchasing behavior.*/

-- 1. How many unique customers have placed orders?
SELECT COUNT(DISTINCT CustomerID) AS unique_customers
FROM orders;
-- 2. Which customers have placed the highest number of orders?
SELECT o.CustomerID, c.Name, COUNT(o.OrderID) AS total_orders
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
GROUP BY o.CustomerID, c.Name
ORDER BY total_orders DESC;

-- 3. What is the total and average purchase value per customer?
SELECT o.CustomerID, c.Name,
       SUM(od.TotalPrice) AS total_spent,
       AVG(od.TotalPrice) AS avg_spent
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY o.CustomerID, c.Name;
-- 4. Who are the top 5 customers by total purchase amount?
SELECT o.CustomerID, c.Name,
       SUM(od.TotalPrice) AS total_spent
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY o.CustomerID, c.Name
ORDER BY total_spent DESC
LIMIT 5;



/*
2. Product Performance
Evaluate how well products are performing in terms of sales and revenue.
*/
-- 1. How many products exist in each category?
SELECT p.CategoryID, c.CategoryName, COUNT(*) AS total_products
FROM products p
JOIN categories c ON p.CategoryID = c.CategoryID
GROUP BY p.CategoryID, c.CategoryName
ORDER BY total_products desc;

-- 2. What is the average price of products by category?
SELECT p.CategoryID, c.CategoryName, AVG(p.Price) AS avg_price
FROM products p
JOIN categories c ON p.CategoryID = c.CategoryID
GROUP BY p.CategoryID, c.CategoryName;

-- 3. Which products have the highest total sales volume (by quantity)?
SELECT od.ProductID, p.Name, SUM(od.Quantity) AS total_sold
FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
GROUP BY od.ProductID, p.Name
ORDER BY total_sold DESC;


-- 4. What is the total revenue generated by each product?
SELECT od.ProductID, p.Name, SUM(od.TotalPrice) AS revenue
FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
GROUP BY od.ProductID, p.Name
ORDER BY revenue DESC;

-- 5.How do product sales vary by category and supplier?
SELECT p.CategoryID, c.CategoryName,
       p.SupplierID, s.SupplierName,
       SUM(od.TotalPrice) AS revenue
FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
JOIN categories c ON p.CategoryID = c.CategoryID
JOIN supplier s ON p.SupplierID = s.SupplierID
GROUP BY p.CategoryID, c.CategoryName, p.SupplierID, s.SupplierName
ORDER BY revenue DESC;


/*
3. Sales and Order Trends
Analyze business performance through orders and revenue over time.
*/
-- 1. How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;

-- 2. What is the average value per order?
SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT OrderID, SUM(TotalPrice) AS order_total
    FROM order_details
    GROUP BY OrderID
) t;

-- 3. On which dates were the most orders placed?
SELECT OrderDate, COUNT(*) AS total_orders
FROM orders
GROUP BY OrderDate
ORDER BY total_orders DESC;


-- 4. What are the monthly trends in order volume and revenue?
SELECT 
    YEAR(o.OrderDate) AS year,
    MONTH(o.OrderDate) AS month,
    COUNT(DISTINCT o.OrderID) AS total_orders,
    SUM(od.TotalPrice) AS total_revenue
FROM orders o
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY year, month
ORDER BY year, month;
-- 5. How do order patterns vary across weekdays and weekends?
SELECT 
    CASE 
        WHEN DAYOFWEEK(OrderDate) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;



/* 
4️. Supplier Contribution
Identify the most active and profitable suppliers.
*/
-- 1. How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- 2. Which supplier provides the most products?
SELECT p.SupplierID, s.SupplierName, COUNT(p.ProductID) AS total_products
FROM products p
JOIN supplier s ON p.SupplierID = s.SupplierID
GROUP BY p.SupplierID, s.SupplierName
ORDER BY total_products DESC;


-- 3. What is the average price of products from each supplier?
SELECT p.SupplierID, s.SupplierName, AVG(p.Price) AS avg_price
FROM products p
JOIN supplier s ON p.SupplierID = s.SupplierID
GROUP BY p.SupplierID, s.SupplierName;

-- 4. Which suppliers contribute the most to total product sales (by revenue)?
SELECT p.SupplierID, s.SupplierName,
       SUM(od.TotalPrice) AS revenue
FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
JOIN supplier s ON p.SupplierID = s.SupplierID
GROUP BY p.SupplierID, s.SupplierName
ORDER BY revenue DESC;

/*
5️. Employee Performance
Assess how employees are handling and influencing sales.
*/
-- 1. How many employees have processed orders?
SELECT COUNT(DISTINCT EmployeeID) AS active_employees
FROM orders;

-- 2. Which employees have handled the most orders?
SELECT o.EmployeeID, e.Name, COUNT(o.OrderID) AS total_orders
FROM orders o
JOIN employees e ON o.EmployeeID = e.EmployeeID
GROUP BY o.EmployeeID, e.Name
ORDER BY total_orders DESC;	

-- 3. What is the total sales value processed by each employee?
SELECT o.EmployeeID, e.Name,
       SUM(od.TotalPrice) AS total_sales
FROM orders o
JOIN employees e ON o.EmployeeID = e.EmployeeID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY o.EmployeeID, e.Name
ORDER BY total_sales DESC;

-- 4. What is the average order value handled per employee?
SELECT EmployeeID, Name,
       AVG(order_total) AS avg_order_value
FROM (
    SELECT o.EmployeeID, e.Name,
           o.OrderID,
           SUM(od.TotalPrice) AS order_total
    FROM orders o
    JOIN employees e ON o.EmployeeID = e.EmployeeID
    JOIN order_details od ON o.OrderID = od.OrderID
    GROUP BY o.EmployeeID, e.Name, o.OrderID
) t
GROUP BY EmployeeID, Name;


/*
6️. Order Details Deep Dive
Explore item-level sales patterns and pricing behavior.
*/
-- 1.What is the relationship between quantity ordered and total price?
SELECT Quantity, AVG(TotalPrice) AS avg_price
FROM order_details
GROUP BY Quantity;

-- 2.What is the average quantity ordered per product?
SELECT od.ProductID, p.Name, AVG(od.Quantity) AS avg_quantity
FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
GROUP BY od.ProductID, p.Name;

-- 3. How does the unit price vary across products and orders?
SELECT od.ProductID, p.Name,
       MIN(od.PriceEach) AS min_price,
       MAX(od.PriceEach) AS max_price
FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
GROUP BY od.ProductID, p.Name;

